export const Actions = {
    INCREASE_COUNTER: "INCREASE_COUNTER",
    DECREASE_COUNTER: "DECREASE_COUNTER",
    ADD_COUNTER: "ADD_COUNTER",
    REMOVE_COUNTER: "REMOVE_COUNTER",

    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_POSITIVE: 'SHOW_POSITIVE',
  SHOW_NEGATIVE: 'SHOW_NEGATIVE',
  SHOW_ZEROS: 'SHOW_ZEROS'
}